services:
  point_database:
    image: postgres
    volumes:
        - pgdata:/var/lib/postgresql
    environment:
        POSTGRES_USER: LennonDev
        POSTGRES_DB: point_db
        POSTGRES_PASSWORD: Secretpoint
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U LennonDev -d point_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  fast_point_app:
    image: fast_point_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
        - "8000:8000"
    depends_on:
      point_database:
        condition: service_healthy
    environment:
        DATABASE_URL: "postgresql+psycopg://LennonDev:Secretpoint@point_database:5432/point_db"


volumes:
  pgdata: