name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copias os arquivos do repositorio
        uses: actions/checkout@v4

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar o poetry
        run: |
          pipx install poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar dependÃªncias
        run: poetry install

      - name: Executar o linter
        run: poetry run task lint

      - name: Executar testes
        run: poetry run task test

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE: ${{ secrets.ACCESS_TOKEN_EXPIRE }}